#############################################################################################
########################################## spring ###########################################
#############################################################################################
spring:
  application:
    name: spring-boot-api-version-demo
#############################################################################################
########################################## server ###########################################
#############################################################################################
server:
  port: 5200